### ISSUE TITLE
Mod doesn't work properly since patch 1.63

### ISSUE THREAD

**Issue by BenjaminCap2** [justarandomguyintheinternet/CP77_nativeSettings#7]
Hello, this mod doesn't work since patch 1.63 of CP2077. 
Indeed, the mod load but it display a message "No mods available" in the 'Mod settings' menu.

In the CET console we can read this interesting line : 

`Function OnSavesReady in class SingleplayerMenuGameController does not exist`  ( in red )

The nativeSettings.log file is empty and the only clue we can get is this red line in CET console. 
Apart from that it seems that the mod load correctly because of these lines : 

`Mod nativeSettings loaded! ('C:\Program Files\EpicGames\Cyberpunk2077\bin\x64\plugins\cyber_engine_tweaks\mods\nativeSettings')`

`[NativeSettings] NativeSettings lib initialized!`

You'll find in attachment file the necessary screenshots to understand the issue.

NB: CET version is 1.25.2 ( released on 28 jun 2023 ) and Native Settings UI version is 1.94 ( released on 08 Jul 2023 ).

Thanks
![Capture d’écran (135)](https://github.com/justarandomguyintheinternet/CP77_nativeSettings/assets/82703909/f290b97e-65b1-40e9-8c65-c32e7b7b0c87)
![Capture d’écran (136)_LI](https://github.com/justarandomguyintheinternet/CP77_nativeSettings/assets/82703909/bfd06cd3-2d46-46c6-851c-bd84beb483c5)

**Comment by justarandomguyintheinternet** [comment]
This is not a warning thrown by this mod, as it does not even use that function. Also, the screenshot you attached shows Mod Settings, not Native Settings UI.
